config/routes.rb
Rails.application.routes.draw do
  
  root to: 'activities#index'

  resources :attendees  

  resources :activities

  devise_for :users, :controllers => { registrations: 'registrations' }

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user

  has_many :joinings, dependent: :destroy
  has_many :attendees, through: :joinings
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base

	has_many :joinings, dependent: :destroy
  has_many :activities, through: :joinings

end

app/models/joining.rb
class Joining < ActiveRecord::Base
  belongs_to :activity
  belongs_to :attendee
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :activities
  
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  respond_to :html



  def index
    @activity = Activity.new
    @activities = Activity.all
    @users = User.all
    @attendee = Attendee.new
    @attendees = Attendee.all


    respond_with(@activities)
  end


  def edit
  end

  def create

    @activity = Activity.new(activity_params)
    @activity.user_id = current_user.id   #current_username is a DEVISE parameter
    @activity.save
    redirect_to activities_path
  end

  def update
    @activity.update(activity_params)
    redirect_to activities_path
  end

  def destroy
    @activity.destroy
    redirect_to activities_path
  end

  private
    def set_activity
      @activity = Activity.find(params[:id])
    end

    def activity_params
      params.require(:activity).permit(:description, :User_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!  # to require auth for all actions (devise)
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def create

    activity = Activity.find(params[:id])
    @attendee = activity.attendees.create user_id: current_user.id.to_i


    redirect_to activities_path
  end



  def destroy
    @attendee = Attendee.find(params[:id])
    @attendee.destroy
    
    redirect_to activities_path
  end

  private
    def set_attendee
      @attendee = Attendee.find(params[:id])
    end

    def attendee_params
      params.require(:attendee).permit(:user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController		#check this for info: http://www.jacopretorius.net/2014/03/adding-custom-fields-to-your-devise-user-model-in-rails-4.html
	#also read the readme file 
  private
 
  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
 
  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>


  <tbody>
    <% @activities.each do |activity| %>

      <tr>
        <td><h3 style="color:blue">Activity Desctription: </h3></td>
      </tr>
      <tr>
        <td><strong><%= activity.description %></strong></td>

        <% if activity.user_id.to_i == current_user.id %> 
        <!-- delete only if current user creatd the event -->
          <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
          <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>

      <tr>
        <td><h4 style="color:red">Created By: </h4></td>

        <td><h4><%= @users.find(activity.user_id.to_i).username %></h4></td>
      </tr>

      <tr>
        
          <td><h4 style="color:green">People Joining: </h4></td>
          <% activity.attendees.each do |attendee| %>
          <td><text> <%= @users.find(attendee.user_id).username.to_s %> , </text></td>
          <% end %>

      </tr>      

      <tr>
        <td>

        <% if activity.attendees.where("user_id is ?" , current_user).blank?  %> 
              <!-- .blank? returns if the DB query has any rows inside or not -->

          <%= button_to 'Join', attendees_path(:id => activity) %>
              <!-- store the activity id, to be used in Many to Many relation in Attendees controller - method Create -->

        <% else %>

          <%= button_to 'Unattend', attendee_path(activity.attendees.where("user_id is ?" , current_user).first.id), method: :delete %>
                <!-- finding the path to the created attendee for the specific activity
                Search an easier way?!?
                Until then that will work too -->

        <% end %>

        </td>
      </tr>


      <tr>
        <td>____________________________</td>
      </tr>




    <% end %>
  </tbody>
</table>

<br>



<h1>New activity</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AttendActivitiesRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<% if user_signed_in? %>
  <div>
  logged in as : <strong><%= current_user.username %></strong>     <!-- current_username is a DEVISE parameter -->
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </div>

<% end %>

<%= yield %>

</body>
</html>